#!/usr/bin/env bash
# OPTIONAL — Lakadiya's backend currently serves uploads from local disk
# (lakadiya/backend/uploads/, via multer), not S3. Skip this script unless
# you're deliberately migrating file storage to S3 first; 03-deploy-app.sh
# does not read credentials.txt's S3 keys today. Kept here only so the
# option exists later without redesigning the deploy pipeline.
# Safe to re-run: skips anything that already exists.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

# shellcheck source=config.env
source ./config.env

echo "== Region: $AWS_REGION | Bucket: $S3_BUCKET | IAM user: $IAM_USER_NAME =="

# ── Bucket ───────────────────────────────────────────────────────────────
if aws s3api head-bucket --bucket "$S3_BUCKET" 2>/dev/null; then
  echo "Bucket $S3_BUCKET already exists — skipping create."
else
  if [ "$AWS_REGION" = "us-east-1" ]; then
    aws s3api create-bucket --bucket "$S3_BUCKET" --region "$AWS_REGION"
  else
    aws s3api create-bucket --bucket "$S3_BUCKET" --region "$AWS_REGION" \
      --create-bucket-configuration LocationConstraint="$AWS_REGION"
  fi
  echo "Created bucket $S3_BUCKET."
fi

aws s3api put-public-access-block --bucket "$S3_BUCKET" --public-access-block-configuration \
  'BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false'

aws s3api put-bucket-policy --bucket "$S3_BUCKET" --policy "$(cat <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [{
    "Sid": "PublicReadForPublicPrefix",
    "Effect": "Allow",
    "Principal": "*",
    "Action": "s3:GetObject",
    "Resource": "arn:aws:s3:::${S3_BUCKET}/public/*"
  }]
}
POLICY
)"
echo "Public-read policy applied to s3://$S3_BUCKET/public/*."

# ── IAM user scoped to just this bucket ─────────────────────────────────
if aws iam get-user --user-name "$IAM_USER_NAME" >/dev/null 2>&1; then
  echo "IAM user $IAM_USER_NAME already exists — skipping create."
else
  aws iam create-user --user-name "$IAM_USER_NAME"
  echo "Created IAM user $IAM_USER_NAME."
fi

aws iam put-user-policy --user-name "$IAM_USER_NAME" --policy-name "${IAM_USER_NAME}-s3-access" --policy-document "$(cat <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["s3:PutObject", "s3:GetObject", "s3:DeleteObject"],
      "Resource": "arn:aws:s3:::${S3_BUCKET}/*"
    },
    {
      "Effect": "Allow",
      "Action": "s3:ListBucket",
      "Resource": "arn:aws:s3:::${S3_BUCKET}"
    }
  ]
}
POLICY
)"

if [ -f ./credentials.txt ] && grep -q S3_ACCESS_KEY_ID ./credentials.txt; then
  echo "credentials.txt already has an access key — not creating another."
  echo "Delete credentials.txt (and the old key via 'aws iam list-access-keys --user-name $IAM_USER_NAME') to rotate."
else
  KEY_JSON=$(aws iam create-access-key --user-name "$IAM_USER_NAME")
  ACCESS_KEY_ID=$(echo "$KEY_JSON" | grep -o '"AccessKeyId": *"[^"]*"' | cut -d'"' -f4)
  SECRET_KEY=$(echo "$KEY_JSON" | grep -o '"SecretAccessKey": *"[^"]*"' | cut -d'"' -f4)
  cat > ./credentials.txt <<EOF
# Generated by 01-setup-s3.sh. Not committed (gitignored).
S3_REGION=$AWS_REGION
S3_BUCKET=$S3_BUCKET
S3_ACCESS_KEY_ID=$ACCESS_KEY_ID
S3_SECRET_ACCESS_KEY=$SECRET_KEY
EOF
  echo "Access key written to credentials.txt."
fi

echo "== S3 setup done =="
