#!/usr/bin/env bash
# Launches one EC2 instance for a testing-only Lakadiya deploy: security
# group (SSH from your IP only, app ports open for direct testing — no
# nginx/TLS yet, this is not meant to be production-hardened), a fresh key
# pair, and a stable Elastic IP so the sslip.io hostname doesn't change on
# reboot. Safe to re-run: skips anything that already exists.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

# shellcheck source=config.env
source ./config.env
export AWS_DEFAULT_REGION="$AWS_REGION"

if [ -z "$SSH_CIDR" ]; then
  MY_IP=$(curl -s https://checkip.amazonaws.com)
  SSH_CIDR="${MY_IP}/32"
  echo "SSH_CIDR not set — using your current public IP: $SSH_CIDR"
fi

# ── Key pair ─────────────────────────────────────────────────────────────
if aws ec2 describe-key-pairs --key-names "$KEY_NAME" >/dev/null 2>&1; then
  echo "Key pair $KEY_NAME already exists — reusing (make sure you still have ${KEY_NAME}.pem locally, in this same folder)."
else
  aws ec2 create-key-pair --key-name "$KEY_NAME" --query 'KeyMaterial' --output text > "./${KEY_NAME}.pem"
  chmod 400 "./${KEY_NAME}.pem"
  echo "Created key pair, saved to ./${KEY_NAME}.pem — do not commit this file."
fi

# ── Security group (default VPC) ────────────────────────────────────────
VPC_ID=$(aws ec2 describe-vpcs --filters Name=isDefault,Values=true --query 'Vpcs[0].VpcId' --output text)

SG_ID=$(aws ec2 describe-security-groups --filters Name=group-name,Values="$SECURITY_GROUP_NAME" Name=vpc-id,Values="$VPC_ID" \
  --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || echo "None")

if [ "$SG_ID" = "None" ] || [ -z "$SG_ID" ]; then
  SG_ID=$(aws ec2 create-security-group --group-name "$SECURITY_GROUP_NAME" \
    --description "Lakadiya testing-only deploy - not for production" --vpc-id "$VPC_ID" \
    --query 'GroupId' --output text)
  echo "Created security group $SG_ID."

  aws ec2 authorize-security-group-ingress --group-id "$SG_ID" --protocol tcp --port 22 --cidr "$SSH_CIDR" >/dev/null
  # Direct-to-app ports for testing (backend API + admin dashboard) — open
  # to the internet on purpose so you can hit it from a browser/mobile
  # without a reverse proxy. Tear the instance down when you're done testing.
  for PORT in 3000 3001; do
    aws ec2 authorize-security-group-ingress --group-id "$SG_ID" --protocol tcp --port "$PORT" --cidr 0.0.0.0/0 >/dev/null
  done
  echo "Opened 22 (from $SSH_CIDR) and 3000/3001 (from anywhere)."
else
  echo "Security group $SECURITY_GROUP_NAME already exists ($SG_ID) — reusing."
fi

# ── Latest Ubuntu 24.04 LTS AMI ──────────────────────────────────────────
AMI_ID=$(aws ssm get-parameter \
  --name /aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id \
  --query 'Parameter.Value' --output text)
echo "Using AMI $AMI_ID."

# ── User-data: base packages only, app deploy happens in 03-deploy-app.sh ─
USER_DATA_FILE=$(mktemp)
cat > "$USER_DATA_FILE" <<'CLOUDINIT'
#!/usr/bin/env bash
set -euo pipefail

# t3.micro has only 1GB RAM — building the Next.js admin app without swap
# risks the OOM killer taking down the build (or sshd) mid-deploy.
fallocate -l 2G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo '/swapfile none swap sw 0 0' >> /etc/fstab

apt-get update -y
apt-get install -y ca-certificates curl gnupg git

# Postgres — installed natively, matching this app's own local-dev setup
# (no docker-compose.yml here, unlike the gym-management sibling project).
apt-get install -y postgresql

# Node 20 + pm2 (both apps run as plain Node processes, not containers)
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs
npm install -g pm2

touch /home/ubuntu/cloud-init-done
CLOUDINIT

INSTANCE_ID=$(aws ec2 run-instances \
  --image-id "$AMI_ID" \
  --instance-type "$INSTANCE_TYPE" \
  --key-name "$KEY_NAME" \
  --security-group-ids "$SG_ID" \
  --user-data "file://$USER_DATA_FILE" \
  --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$INSTANCE_NAME}]" \
  --block-device-mappings '[{"DeviceName":"/dev/sda1","Ebs":{"VolumeSize":20,"VolumeType":"gp3"}}]' \
  --query 'Instances[0].InstanceId' --output text)
rm -f "$USER_DATA_FILE"
echo "Launched instance $INSTANCE_ID — waiting for it to be running..."
aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"

# ── Elastic IP (stable address so the sslip.io hostname survives reboots) ─
ALLOC_ID=$(aws ec2 allocate-address --domain vpc --query 'AllocationId' --output text)
aws ec2 associate-address --instance-id "$INSTANCE_ID" --allocation-id "$ALLOC_ID" >/dev/null
PUBLIC_IP=$(aws ec2 describe-addresses --allocation-ids "$ALLOC_ID" --query 'Addresses[0].PublicIp' --output text)

SSLIP_DOMAIN="${PUBLIC_IP//./-}.sslip.io"

cat >> ./credentials.txt <<EOF

# Generated by 02-launch-ec2.sh
INSTANCE_ID=$INSTANCE_ID
SECURITY_GROUP_ID=$SG_ID
ELASTIC_IP_ALLOCATION_ID=$ALLOC_ID
PUBLIC_IP=$PUBLIC_IP
TEST_DOMAIN=$SSLIP_DOMAIN
EOF

echo "== EC2 launched =="
echo "Public IP:   $PUBLIC_IP"
echo "Test domain: $SSLIP_DOMAIN  (wildcard DNS via sslip.io — no domain purchase needed)"
echo "SSH:         ssh -i ./${KEY_NAME}.pem ubuntu@${PUBLIC_IP}"
echo "Wrote these to credentials.txt. Cloud-init (Postgres/Node/pm2 install) takes ~1-2 min after boot —"
echo "check with: ssh -i ./${KEY_NAME}.pem ubuntu@${PUBLIC_IP} 'ls ~/cloud-init-done'"
